import type {
  AccessCase,
  ActivityItem,
  AgentProfile,
  Project,
  User,
} from "./types";

export const USERS: User[] = [
  {
    id: "u-op",
    name: "Sarah Chen",
    email: "sarah@northerngrid.example",
    role: "operator",
    org: "Northern Grid Alliance",
    title: "Land Access Manager",
    initials: "SC",
  },
  {
    id: "u-ag",
    name: "James Whitfield",
    email: "james@whitfieldland.example",
    role: "agent",
    org: "Whitfield Land",
    title: "Principal Land Agent",
    initials: "JW",
  },
  {
    id: "u-lo",
    name: "Margaret Ellis",
    email: "margaret@ellisfarm.example",
    role: "landowner",
    org: "Ellis Farm",
    title: "Landowner",
    initials: "ME",
  },
];

export const AGENTS: AgentProfile[] = [
  {
    id: "ag-whitfield",
    userId: "u-ag",
    name: "James Whitfield",
    firm: "Whitfield Land",
    counties: ["Lincolnshire", "Nottinghamshire", "Rutland"],
    specialisms: ["rail", "electricity", "renewables"],
    rating: 4.9,
    casesClosed: 214,
    capacity: "available",
    dayRate: 520,
  },
  {
    id: "ag-harper",
    userId: "u-harper",
    name: "Priya Harper",
    firm: "Harper Rights",
    counties: ["Cambridgeshire", "Lincolnshire", "Norfolk"],
    specialisms: ["telecom", "water", "environment"],
    rating: 4.8,
    casesClosed: 167,
    capacity: "limited",
    dayRate: 480,
  },
  {
    id: "ag-osborne",
    userId: "u-osborne",
    name: "Tom Osborne",
    firm: "Osborne & Co",
    counties: ["Yorkshire", "Lincolnshire"],
    specialisms: ["highways", "rail", "water"],
    rating: 4.7,
    casesClosed: 301,
    capacity: "available",
    dayRate: 495,
  },
  {
    id: "ag-nash",
    userId: "u-nash",
    name: "Elena Nash",
    firm: "Nash Access",
    counties: ["Lincolnshire", "Leicestershire"],
    specialisms: ["renewables", "electricity"],
    rating: 4.9,
    casesClosed: 92,
    capacity: "full",
    dayRate: 550,
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p-gi",
    name: "East Coast GI Corridor",
    code: "ECML-GI-26",
    sector: "rail",
    client: "Network Rail (via Northern Grid Alliance)",
    county: "Lincolnshire",
    startDate: "2026-06-01",
    endDate: "2026-11-30",
    description:
      "Ground investigation boreholes and trial pits along the East Coast corridor to inform electrification civils.",
    caseIds: ["c-ellis", "c-harrowby", "c-welbourn", "c-leadenham", "c-caythorpe", "c-ancaster"],
  },
  {
    id: "p-solar",
    name: "Fenland Solar Access",
    code: "FEN-SOL-26",
    sector: "renewables",
    client: "Fenland Energy Ltd",
    county: "Lincolnshire",
    startDate: "2026-04-15",
    endDate: "2027-03-31",
    description:
      "Temporary construction access, compound and cable easement for a 49MW solar farm.",
    caseIds: ["c-stubton", "c-rippingale"],
  },
  {
    id: "p-a15",
    name: "A15 Culvert Replacement",
    code: "A15-CUL-26",
    sector: "highways",
    client: "National Highways contractor",
    county: "Lincolnshire",
    startDate: "2026-07-01",
    endDate: "2026-10-15",
    description: "Off-highway working room and farm access for culvert replacement.",
    caseIds: ["c-witham", "c-brant"],
  },
  {
    id: "p-132",
    name: "132kV Cable Diversion",
    code: "DNO-132-26",
    sector: "electricity",
    client: "Regional DNO",
    county: "Lincolnshire",
    startDate: "2026-05-01",
    endDate: "2026-12-20",
    description: "Underground cable pull and overhead survey across third-party land.",
    caseIds: ["c-folkingham", "c-fulbeck", "c-claypole"],
  },
  {
    id: "p-fibre",
    name: "Rural Fibre Spine",
    code: "FIB-LINCS-26",
    sector: "telecom",
    client: "Openreach contractor",
    county: "Lincolnshire",
    startDate: "2026-03-01",
    endDate: "2026-09-30",
    description: "Duct and chamber access along a rural fibre spine.",
    caseIds: ["c-marston", "c-billingborough", "c-beckingham"],
  },
];

function poly(lat: number, lng: number, dx = 0.012, dy = 0.008): [number, number][] {
  return [
    [lat - dy, lng - dx],
    [lat - dy, lng + dx],
    [lat + dy, lng + dx],
    [lat + dy, lng - dx],
  ];
}

export const CASES: AccessCase[] = [
  {
    id: "c-ellis",
    ref: "AML-2026-0142",
    projectId: "p-gi",
    parcel: {
      id: "par-ellis",
      title: "Ellis Farm, north arable",
      osGrid: "SK 974 436",
      areaHa: 18.4,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.018,
      lng: -0.548,
      polygon: poly(53.018, -0.548, 0.016, 0.01),
    },
    status: "negotiating",
    accessType: "gi_borehole",
    durationDays: 2,
    disturbance: "Tracked rig, 4x4 and welfare van. Two boreholes to 15m.",
    cropImpact: "Winter wheat. Access after harvest preferred; compensatory yield loss if earlier.",
    owner: {
      id: "pt-ellis",
      name: "Margaret Ellis",
      role: "owner",
      org: "Ellis Farm",
      email: "margaret@ellisfarm.example",
      phone: "01522 441 208",
      userId: "u-lo",
    },
    offers: [
      {
        id: "o1",
        from: "operator",
        amount: 650,
        conditions: "Two boreholes, 48-hour window, access from the farm track, reinstatement of wheelings.",
        at: "2026-08-18T09:14:00",
        author: "Sarah Chen",
      },
      {
        id: "o2",
        from: "landowner",
        amount: 950,
        conditions: "Must be after harvest. No night working. Gate to be left as found. Additional £200 if crop is entered.",
        at: "2026-08-21T16:40:00",
        author: "Margaret Ellis",
      },
      {
        id: "o3",
        from: "operator",
        amount: 780,
        conditions: "Visit after harvest (w/c 14 Sep). Daylight hours only. Crop clause dropped if we wait.",
        at: "2026-08-26T11:05:00",
        author: "Sarah Chen",
      },
    ],
    conditions: [
      { id: "cd1", text: "Access after harvest, week commencing 14 September 2026", agreed: true },
      { id: "cd2", text: "Daylight hours only; no weekend working", agreed: true },
      { id: "cd3", text: "Reinstatement of wheelings within 7 days", agreed: false },
      { id: "cd4", text: "RAMS and insurance certificate issued 5 days before entry", agreed: true },
    ],
    evidence: [],
    lastActivity: "2026-08-26T11:05:00",
    notes: "Key demonstration file. Landowner is on the platform.",
  },
  {
    id: "c-harrowby",
    ref: "AML-2026-0148",
    projectId: "p-gi",
    parcel: {
      id: "par-harr",
      title: "Harrowby pasture",
      osGrid: "SK 941 352",
      areaHa: 6.2,
      landUse: "pasture",
      county: "Lincolnshire",
      lat: 52.941,
      lng: -0.598,
      polygon: poly(52.941, -0.598),
    },
    status: "terms_agreed",
    accessType: "gi_borehole",
    durationDays: 1,
    disturbance: "Single borehole, rubber-tracked rig.",
    cropImpact: "None — permanent pasture. Livestock to be moved.",
    owner: {
      id: "pt-harr",
      name: "David Crowe",
      role: "owner",
      org: "Harrowby Grazing",
      email: "david.crowe@example.com",
      phone: "01476 552 019",
    },
    offers: [
      { id: "o1", from: "operator", amount: 580, conditions: "One borehole, livestock moved by owner.", at: "2026-08-04T10:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 720, conditions: "Include handling of cattle.", at: "2026-08-06T09:22:00", author: "David Crowe" },
      { id: "o3", from: "operator", amount: 690, conditions: "Owner moves stock; we pay handling.", at: "2026-08-08T14:10:00", author: "Sarah Chen" },
    ],
    conditions: [
      { id: "cd1", text: "Livestock moved the evening before", agreed: true },
      { id: "cd2", text: "Gates chained on exit", agreed: true },
    ],
    evidence: [],
    lastActivity: "2026-08-08T14:10:00",
    notes: "",
  },
  {
    id: "c-welbourn",
    ref: "AML-2026-0151",
    projectId: "p-gi",
    parcel: {
      id: "par-wel",
      title: "Welbourn cliff field",
      osGrid: "SK 968 543",
      areaHa: 11.1,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.114,
      lng: -0.558,
      polygon: poly(53.114, -0.558),
    },
    status: "offer_made",
    accessType: "trial_pit",
    durationDays: 1,
    disturbance: "Two trial pits, excavator and banksman.",
    cropImpact: "Stubble. Low impact if after harvest.",
    owner: {
      id: "pt-wel",
      name: "Helen Pratt",
      role: "owner",
      email: "h.pratt@example.com",
      phone: "01529 413 770",
    },
    offers: [
      { id: "o1", from: "operator", amount: 520, conditions: "Two trial pits on stubble, backfilled same day.", at: "2026-08-28T08:30:00", author: "Sarah Chen" },
    ],
    conditions: [],
    evidence: [],
    lastActivity: "2026-08-28T08:30:00",
    notes: "",
  },
  {
    id: "c-leadenham",
    ref: "AML-2026-0155",
    projectId: "p-gi",
    parcel: {
      id: "par-lead",
      title: "Leadenham top",
      osGrid: "SK 952 518",
      areaHa: 9.4,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.091,
      lng: -0.582,
      polygon: poly(53.091, -0.582),
    },
    status: "licence_generated",
    accessType: "gi_borehole",
    durationDays: 1,
    disturbance: "One borehole adjacent to the headland.",
    cropImpact: "None if confined to headland.",
    owner: {
      id: "pt-lead",
      name: "Andrew Pell",
      role: "owner",
      email: "a.pell@example.com",
      phone: "01400 273 441",
    },
    offers: [
      { id: "o1", from: "operator", amount: 700, conditions: "Headland only.", at: "2026-08-12T11:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 700, conditions: "Agreed, licence to name occupier as well.", at: "2026-08-13T17:45:00", author: "Andrew Pell" },
    ],
    conditions: [{ id: "cd1", text: "Confine plant to the headland", agreed: true }],
    evidence: [],
    signedByOperator: true,
    licenceGeneratedAt: "2026-08-14T09:00:00",
    lastActivity: "2026-08-14T09:00:00",
    notes: "Awaiting landowner signature.",
  },
  {
    id: "c-caythorpe",
    ref: "AML-2026-0160",
    projectId: "p-gi",
    parcel: {
      id: "par-cay",
      title: "Caythorpe heath",
      osGrid: "SK 938 479",
      areaHa: 22.0,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.056,
      lng: -0.602,
      polygon: poly(53.056, -0.602, 0.02, 0.012),
    },
    status: "owner_identified",
    accessType: "walkover",
    durationDays: 1,
    disturbance: "Two surveyors on foot, no plant.",
    cropImpact: "None.",
    owner: {
      id: "pt-cay",
      name: "Caythorpe Estate Trustees",
      role: "owner",
      email: "estates@caythorpe.example",
      phone: "01400 272 100",
    },
    offers: [],
    conditions: [],
    evidence: [],
    lastActivity: "2026-08-29T15:20:00",
    notes: "Title confirmed via Land Registry. Occupier is the in-hand farming company.",
  },
  {
    id: "c-ancaster",
    ref: "AML-2026-0162",
    projectId: "p-gi",
    parcel: {
      id: "par-anc",
      title: "Ancaster ridge",
      osGrid: "SK 982 435",
      areaHa: 7.8,
      landUse: "woodland",
      county: "Lincolnshire",
      lat: 53.017,
      lng: -0.536,
      polygon: poly(53.017, -0.536),
    },
    status: "marketplace",
    accessType: "ecological",
    durationDays: 1,
    disturbance: "Ecologist walkover, no plant.",
    cropImpact: "None.",
    owner: {
      id: "pt-anc",
      name: "Unknown — title pending",
      role: "owner",
    },
    offers: [],
    conditions: [],
    evidence: [],
    professionalFee: 480,
    marketplaceFee: 72,
    lastActivity: "2026-08-30T10:00:00",
    notes: "Internal team at capacity. Listed for an independent agent to identify owner and complete access.",
  },
  {
    id: "c-stubton",
    ref: "AML-2026-0110",
    projectId: "p-solar",
    parcel: {
      id: "par-stub",
      title: "Stubton south",
      osGrid: "SK 874 487",
      areaHa: 34.6,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.064,
      lng: -0.698,
      polygon: poly(53.064, -0.698, 0.024, 0.014),
    },
    status: "negotiating",
    accessType: "compound",
    durationDays: 120,
    disturbance: "Welfare compound, parking and wheel wash for 16 weeks.",
    cropImpact: "Takes 0.6ha out of cropping for one season.",
    owner: {
      id: "pt-stub",
      name: "Robert & Jane Langley",
      role: "owner",
      org: "Langley Farms",
      email: "office@langleyfarms.example",
      phone: "01636 626 441",
    },
    offers: [
      { id: "o1", from: "operator", amount: 4800, conditions: "16-week compound, full reinstatement, topsoil stripped and stored.", at: "2026-08-02T09:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 7200, conditions: "Plus crop loss at 2025 yield × Nov price, and a bond.", at: "2026-08-09T18:12:00", author: "Robert Langley" },
      { id: "o3", from: "operator", amount: 5600, conditions: "Compound fee plus separate crop-loss calculation on actual area.", at: "2026-08-19T12:40:00", author: "Sarah Chen" },
    ],
    conditions: [
      { id: "cd1", text: "Topsoil stripped, stored and replaced", agreed: true },
      { id: "cd2", text: "Wheel wash to prevent soil on the lane", agreed: true },
      { id: "cd3", text: "£10,000 reinstatement bond", agreed: false },
    ],
    evidence: [],
    lastActivity: "2026-08-19T12:40:00",
    notes: "Highest-value live negotiation.",
  },
  {
    id: "c-rippingale",
    ref: "AML-2026-0098",
    projectId: "p-solar",
    parcel: {
      id: "par-rip",
      title: "Rippingale Fen",
      osGrid: "TF 145 278",
      areaHa: 12.2,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 52.835,
      lng: -0.302,
      polygon: poly(52.835, -0.302),
    },
    status: "closed",
    accessType: "construction",
    durationDays: 14,
    disturbance: "Haul route across headland.",
    cropImpact: "Headland only.",
    owner: {
      id: "pt-rip",
      name: "Fenland Trustees",
      role: "owner",
      email: "fenland@example.com",
    },
    offers: [
      { id: "o1", from: "operator", amount: 3200, conditions: "Two-week haul route.", at: "2026-06-02T10:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 3900, conditions: "Include stone to the gateway.", at: "2026-06-04T11:00:00", author: "Fenland Trustees" },
      { id: "o3", from: "operator", amount: 3900, conditions: "Agreed with stone.", at: "2026-06-05T09:00:00", author: "Sarah Chen" },
    ],
    conditions: [{ id: "cd1", text: "Stone to the gateway, removed on exit", agreed: true }],
    evidence: [
      { id: "e1", kind: "photo", label: "Entry photograph — gateway", at: "2026-07-01T07:50:00", by: "Site team" },
      { id: "e2", kind: "photo", label: "Exit photograph — reinstated", at: "2026-07-14T16:10:00", by: "Site team" },
    ],
    paidAmount: 3900,
    paidAt: "2026-07-18T10:00:00",
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-06-06T09:00:00",
    lastActivity: "2026-07-18T10:00:00",
    notes: "",
  },
  {
    id: "c-witham",
    ref: "AML-2026-0170",
    projectId: "p-a15",
    parcel: {
      id: "par-with",
      title: "Witham Bank",
      osGrid: "TF 105 478",
      areaHa: 4.1,
      landUse: "pasture",
      county: "Lincolnshire",
      lat: 53.016,
      lng: -0.358,
      polygon: poly(53.016, -0.358, 0.01, 0.006),
    },
    status: "visit_scheduled",
    accessType: "construction",
    durationDays: 8,
    disturbance: "Tracked excavator working from the bank.",
    cropImpact: "None.",
    owner: {
      id: "pt-with",
      name: "Claire Houghton",
      role: "owner",
      email: "claire.houghton@example.com",
      phone: "01205 722 883",
    },
    offers: [
      { id: "o1", from: "operator", amount: 2400, conditions: "Eight days on the bank.", at: "2026-08-01T09:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 2400, conditions: "Accepted.", at: "2026-08-02T08:10:00", author: "Claire Houghton" },
    ],
    conditions: [{ id: "cd1", text: "No plant in the watercourse", agreed: true }],
    visit: {
      date: "2026-09-04",
      window: "07:00–17:00",
      team: "A15 civils gang 2",
      notes: "Enter from the farm track, not the A15.",
    },
    evidence: [],
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-08-03T09:00:00",
    lastActivity: "2026-08-22T13:00:00",
    notes: "",
  },
  {
    id: "c-brant",
    ref: "AML-2026-0174",
    projectId: "p-a15",
    parcel: {
      id: "par-brant",
      title: "Brant Broughton verge",
      osGrid: "SK 916 542",
      areaHa: 0.4,
      landUse: "roadside",
      county: "Lincolnshire",
      lat: 53.113,
      lng: -0.636,
      polygon: poly(53.113, -0.636, 0.006, 0.003),
    },
    status: "contacted",
    accessType: "walkover",
    durationDays: 1,
    disturbance: "Surveyors only.",
    cropImpact: "None.",
    owner: {
      id: "pt-brant",
      name: "Broughton Parish",
      role: "owner",
      email: "clerk@brantbroughton.example",
    },
    offers: [],
    conditions: [],
    evidence: [],
    lastActivity: "2026-08-27T11:30:00",
    notes: "Letter and email sent. Awaiting reply.",
  },
  {
    id: "c-folkingham",
    ref: "AML-2026-0133",
    projectId: "p-132",
    parcel: {
      id: "par-folk",
      title: "Folkingham arable",
      osGrid: "TF 072 337",
      areaHa: 15.7,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 52.888,
      lng: -0.407,
      polygon: poly(52.888, -0.407),
    },
    status: "payment_pending",
    accessType: "cable_pull",
    durationDays: 5,
    disturbance: "Open-cut cable, 80m, then backfill.",
    cropImpact: "Strip through winter barley stubble.",
    owner: {
      id: "pt-folk",
      name: "Simon Wade",
      role: "owner",
      email: "s.wade@example.com",
      phone: "01529 497 220",
    },
    offers: [
      { id: "o1", from: "operator", amount: 1250, conditions: "Five-day cable pull.", at: "2026-07-10T09:00:00", author: "Sarah Chen" },
      { id: "o2", from: "landowner", amount: 1600, conditions: "Include extra for drainage crossings.", at: "2026-07-14T19:00:00", author: "Simon Wade" },
      { id: "o3", from: "operator", amount: 1450, conditions: "Drainage crossings included.", at: "2026-07-16T10:20:00", author: "Sarah Chen" },
    ],
    conditions: [{ id: "cd1", text: "Land drains marked before dig", agreed: true }],
    evidence: [
      { id: "e1", kind: "photo", label: "Trench open — chainage 0–80", at: "2026-08-11T12:00:00", by: "Cable gang" },
      { id: "e2", kind: "gps", label: "As-laid GPS track", at: "2026-08-14T16:40:00", by: "Cable gang" },
    ],
    damage: {
      description: "Two land-drain breaks on chainage 42 and 67.",
      estimate: 380,
      reinstatement: "Drains repaired 15 Aug. Headland still to be rolled.",
      at: "2026-08-15T09:30:00",
    },
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-07-17T09:00:00",
    lastActivity: "2026-08-20T09:00:00",
    notes: "Compensation £1,450 + damage £380 = £1,830 due.",
  },
  {
    id: "c-fulbeck",
    ref: "AML-2026-0139",
    projectId: "p-132",
    parcel: {
      id: "par-ful",
      title: "Fulbeck airfield edge",
      osGrid: "SK 948 504",
      areaHa: 8.9,
      landUse: "set_aside",
      county: "Lincolnshire",
      lat: 53.078,
      lng: -0.588,
      polygon: poly(53.078, -0.588),
    },
    status: "access_evidenced",
    accessType: "overhead_survey",
    durationDays: 1,
    disturbance: "Drone survey and two climbers.",
    cropImpact: "None.",
    owner: {
      id: "pt-ful",
      name: "MOD / DIO residual",
      role: "owner",
      email: "dio.estates@example.com",
    },
    offers: [
      { id: "o1", from: "operator", amount: 360, conditions: "Drone + climbing inspection.", at: "2026-08-05T09:00:00", author: "Sarah Chen" },
    ],
    conditions: [{ id: "cd1", text: "NOTAM lodged; no photography of adjacent dwellings", agreed: true }],
    visit: {
      date: "2026-08-25",
      window: "09:00–13:00",
      team: "OHL inspection",
      notes: "",
    },
    evidence: [
      { id: "e1", kind: "photo", label: "Tower 14 — north face", at: "2026-08-25T10:12:00", by: "OHL inspection" },
      { id: "e2", kind: "note", label: "No ground disturbance", at: "2026-08-25T13:05:00", by: "OHL inspection" },
    ],
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-08-06T09:00:00",
    lastActivity: "2026-08-25T13:05:00",
    notes: "",
  },
  {
    id: "c-claypole",
    ref: "AML-2026-0144",
    projectId: "p-132",
    parcel: {
      id: "par-clay",
      title: "Claypole mill field",
      osGrid: "SK 849 490",
      areaHa: 5.5,
      landUse: "pasture",
      county: "Lincolnshire",
      lat: 53.067,
      lng: -0.735,
      polygon: poly(53.067, -0.735),
    },
    status: "signed",
    accessType: "cable_pull",
    durationDays: 3,
    disturbance: "Short HDD shot under the drain.",
    cropImpact: "None.",
    owner: {
      id: "pt-clay",
      name: "Mary Kershaw",
      role: "owner",
      email: "m.kershaw@example.com",
    },
    offers: [
      { id: "o1", from: "operator", amount: 1450, conditions: "HDD under the drain, no open cut.", at: "2026-08-10T09:00:00", author: "Sarah Chen" },
    ],
    conditions: [{ id: "cd1", text: "No open cut within 8m of the watercourse", agreed: true }],
    evidence: [],
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-08-11T09:00:00",
    lastActivity: "2026-08-16T14:00:00",
    notes: "",
  },
  {
    id: "c-marston",
    ref: "AML-2026-0081",
    projectId: "p-fibre",
    parcel: {
      id: "par-mars",
      title: "Marston paddock",
      osGrid: "SK 892 437",
      areaHa: 1.2,
      landUse: "pasture",
      county: "Lincolnshire",
      lat: 53.018,
      lng: -0.671,
      polygon: poly(53.018, -0.671, 0.008, 0.005),
    },
    status: "closed",
    accessType: "cable_pull",
    durationDays: 2,
    disturbance: "Mole-plough duct.",
    cropImpact: "None.",
    owner: {
      id: "pt-mars",
      name: "Ian Marston",
      role: "owner",
      email: "ian.marston@example.com",
    },
    offers: [
      { id: "o1", from: "operator", amount: 420, conditions: "Mole-plough, two days.", at: "2026-05-12T09:00:00", author: "Sarah Chen" },
    ],
    conditions: [],
    evidence: [{ id: "e1", kind: "photo", label: "Duct complete", at: "2026-05-20T15:00:00", by: "Fibre crew" }],
    paidAmount: 420,
    paidAt: "2026-05-28T10:00:00",
    signedByOwner: true,
    signedByOperator: true,
    licenceGeneratedAt: "2026-05-13T09:00:00",
    lastActivity: "2026-05-28T10:00:00",
    notes: "",
  },
  {
    id: "c-billingborough",
    ref: "AML-2026-0166",
    projectId: "p-fibre",
    parcel: {
      id: "par-bill",
      title: "Billingborough fen edge",
      osGrid: "TF 148 342",
      areaHa: 9.8,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 52.892,
      lng: -0.298,
      polygon: poly(52.892, -0.298),
    },
    status: "contacted",
    accessType: "cable_pull",
    durationDays: 3,
    disturbance: "Duct along the droveside.",
    cropImpact: "Headland.",
    owner: {
      id: "pt-bill",
      name: "Nigel Stokes",
      role: "owner",
      email: "nigel.stokes@example.com",
      phone: "01529 240 118",
    },
    assignedAgentId: "ag-whitfield",
    professionalFee: 520,
    marketplaceFee: 78,
    offers: [],
    conditions: [],
    evidence: [],
    lastActivity: "2026-08-25T16:00:00",
    notes: "Claimed by Whitfield Land from the marketplace. First contact made.",
  },
  {
    id: "c-beckingham",
    ref: "AML-2026-0178",
    projectId: "p-fibre",
    parcel: {
      id: "par-beck",
      title: "Beckingham unknown parcel",
      osGrid: "SK 875 538",
      areaHa: 3.3,
      landUse: "arable",
      county: "Lincolnshire",
      lat: 53.11,
      lng: -0.697,
      polygon: poly(53.11, -0.697),
    },
    status: "identifying",
    accessType: "walkover",
    durationDays: 1,
    disturbance: "Walkover only.",
    cropImpact: "None.",
    owner: {
      id: "pt-beck",
      name: "Not yet identified",
      role: "owner",
    },
    offers: [],
    conditions: [],
    evidence: [],
    lastActivity: "2026-08-31T09:00:00",
    notes: "Boundary from scheme GIS. Title search in progress.",
  },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a1", caseId: "c-ellis", at: "2026-08-26T11:05:00", text: "Revised offer of £780 issued — after harvest, daylight only.", by: "Sarah Chen" },
  { id: "a2", caseId: "c-ancaster", at: "2026-08-30T10:00:00", text: "Listed on the agent marketplace for owner identification.", by: "Sarah Chen" },
  { id: "a3", caseId: "c-witham", at: "2026-08-22T13:00:00", text: "Visit scheduled for 4 September, 07:00–17:00.", by: "Sarah Chen" },
  { id: "a4", caseId: "c-folkingham", at: "2026-08-20T09:00:00", text: "Damage recorded — two drain breaks, £380 estimate.", by: "Cable gang" },
  { id: "a5", caseId: "c-billingborough", at: "2026-08-25T16:00:00", text: "Whitfield Land claimed the case from the marketplace.", by: "James Whitfield" },
  { id: "a6", caseId: "c-leadenham", at: "2026-08-14T09:00:00", text: "Access licence generated. Operator signed.", by: "Sarah Chen" },
  { id: "a7", caseId: "c-welbourn", at: "2026-08-28T08:30:00", text: "Opening offer of £520 sent for two trial pits.", by: "Sarah Chen" },
  { id: "a8", caseId: "c-caythorpe", at: "2026-08-29T15:20:00", text: "Owner identified: Caythorpe Estate Trustees.", by: "Sarah Chen" },
];
